### PR TITLE
Require legacy incremental execute as an `ApolloServer` option instead of a dynamic import

### LINKED ISSUE #8159: Turbopack build failed
### Issue Description

In Next.js v16, turbopack became the default.

Building with turbopack in 5.1.0 produces the following error.
There is no issue in 5.0.

```
> Build error occurred
Error: Turbopack build failed with 1 errors:
./node_modules/.pnpm/@apollo+server@5.1.0_graphql@16.12.0/node_modules/@apollo/server/dist/cjs/incrementalDeliveryPolyfill.js:44:75
Module not found: Can't resolve '@yaacovcr/transform'
  42 | async function tryToLoadLegacyExecuteIncrementally() {
  43 |     try {
> 44 |         const transform = await Promise.resolve().then(() => __importStar(require('@yaacovcr/transform')));      
     |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  45 |         legacyExecuteIncrementally = transform.legacyExecuteIncrementally;
  46 |     }
  47 |     catch {
```

https://github.com/apollographql/apollo-server/issues/8004
This issue is likely related.

### Link to Reproduction

https://nextjs.org/docs/app/api-reference/config/next-config-js/turbopack

### Reproduction Steps

_No response_

### PR DESCRIPTION
**Pull request by jerelmiller**
Fixes #8159

Dynamically importing `@yaacovcr/transform` if available has proven to be a difficult solution because some bundlers fail to build when the package isn't installed.

This PR addresses this issue by making the legacy execute function an option that can be provided to the `ApolloServer` constructor. This means no direct dependency on `@yaacovcr/transform` and makes it possible to use other legacy execution functions if available.

To migrate, import the `legacyExecuteIncrementally` and provide it as the `legacyExperimentalExecuteIncrementally` option to the `ApolloServer` constructor.

```ts
import { legacyExecuteIncrementally } from '@yaacovcr/transform';

const server = new ApolloServer({
  // ...
  legacyExperimentalExecuteIncrementally: legacyExecuteIncrementally
})

```

### CODE REVIEW

File: packages/server/src/incrementalDeliveryPolyfill.ts [hunk 1]
```diff
@@ -191,30 +192,8 @@ let graphqlExperimentalExecuteIncrementally:
...
-    ) => PromiseOrValue<
-      ExecutionResult | GraphQLExperimentalIncrementalExecutionResultsAlpha2
-    >)
-  | null
-  | undefined;
-
-async function tryToLoadLegacyExecuteIncrementally() {
-  try {
-    // @ts-ignore `@yaacovcr/transform` is an optional peer dependency
-    const transform = await import('@yaacovcr/transform');
```
Comment (glasser) [inline packages/server/src/incrementalDeliveryPolyfill.ts]: Shouldn't we drop the peer dep?

File: docs/source/workflow/requests.md [hunk 2]
```diff
@@ -145,4 +145,13 @@ You may choose to support the legacy incremental delivery protocol by installing
 npm install @yaacovcr/transform
 ```
 
-There is nothing else to configure. Apollo Server will load the necessary utility if this package is installed.
+You will then need to configure Apollo Server with the `legacyExperimentalExecuteIncrementally` option in order to provide support for the legacy incremental format.
```
Comment (glasser) [inline docs/source/workflow/requests.md]: mention npm install?

File: packages/integration-testsuite/src/httpServerTests.ts [hunk 3]
```diff
@@ -2466,7 +2466,16 @@ export function defineIntegrationTestSuiteHttpServerTests(
               ['multipart/mixed; deferSpec=20220824, application/json'],
               ['application/json, multipart/mixed; deferSpec=20220824'],
             ])('basic @defer working with accept: %s', async (accept) => {
-              const app = await createApp({ typeDefs, resolvers });
+              const { legacyExecuteIncrementally } = await import(
+                // @ts-ignore might not be installed
```
[the remark this answers is not in the document]
Comment (glasser) [reply packages/integration-testsuite/src/httpServerTests.ts]: Just want to make sure you know this is a package that we publish to npm that integration authors can depend on for a test suite (ie it's not only run in the context of this repo's CI) — I think that works with this approach though.
