### PR TITLE
Fix @external validation for complex provides/requires

### LINKED ISSUE #2772: @Provides Directive Unexpected Error
Reproduction Repo: https://github.com/ksaldana1/provides-fed-repro

I am pretty confused by what I am seeing here. I followed the example from the docs, and from what I can tell the structure I have isn't any different from the example provided in the [federation-demo](https://github.com/apollographql/federation-demo/blob/master/services/reviews/index.js), but maybe I'm missing something really obvious.

Despite me [labeling](https://github.com/ksaldana1/provides-fed-repro/blob/master/services/users/index.js#L11) my [fields](https://github.com/ksaldana1/provides-fed-repro/blob/master/services/users/index.js#L17), I'm still getting error messages such as : 
```UnhandledPromiseRejectionWarning: GraphQLSchemaValidationError: [users] Kitchen.name -> is marked as @external but is not used by a @requires, @key, or @provides directive.```

This was happening on a larger project and seemed to continue when I scaled it down. 

Thanks for all your hard work! Federation is really awesome!

### PR DESCRIPTION
**Pull request by JakeDawkins**
Fixes two cases for validation of @external fields
1. If the `@external` field is referenced in a `@provides` on _another type_.
2. If the `@external` field is referenced in a nested selection set within a `@requires`

resolves #2772

### CODE REVIEW

File: packages/apollo-federation/src/composition/validate/postComposition/externalUnused.ts [hunk 1]
```diff
@@ -15,108 +18,183 @@ import {
...
+                  typeToFind: parentType,
+                  fieldToFind: externalFieldName,
+                });
+              });
+            });
+          });
+
+          if (hasMatchingRequiresOnAnotherType) continue;
+
+          const hasMatchingProvidesOrRequiresOnType = Object.values(
```
Comment (trevor-scheer) [inline packages/apollo-federation/src/composition/validate/postComposition/externalUnused.ts]: Is this block still needed? The `xxxOnAnotherType` blocks are looking at the whole schema already, so I think they eliminate the need for this loop.

Comment (JakeDawkins) [reply packages/apollo-federation/src/composition/validate/postComposition/externalUnused.ts]: 😳 I think you just may be right! That's huge

Comment (JakeDawkins) [reply packages/apollo-federation/src/composition/validate/postComposition/externalUnused.ts]: Ah, so close. The `provides` work was an overlap with the original code, so I was able to remove some of that, but the `requires` isn't a direct overlap with the new stuff, so that had to stay in 💀
