### PR TITLE
fix(gateway): merge selection sets of `@requires` fields

### LINKED ISSUE #3848: [Federation Gateway] @requires directive sometimes does not provide all required fields
`@apollo/gateway:0.12.0`

Using the Apollo Federation Demo, lets say we add the following to the `accounts` service schema:
```
type User @key(fields: "id") {
    id: ID!
    name: String
    username: String
    nested1: Nested1
  }

  type Nested1 {
    nested2: Nested2
  }

  type Nested2 {
    a: String
    b: String
  }
```

And let's also add the following to the `reviews` service schema:
```
extend type User @key(fields: "id") {
    id: ID! @external
    username: String @external
    nested1: Nested1 @external
    reviews: [Review] @requires(fields: "nested1 { nested2 { a } }")
    otherField: String @requires(fields: "nested1 { nested2 { b } }")
  }

  type Nested1 {
    nested2: Nested2
  }

  type Nested2 {
    a: String
    b: String
  }
```

In the `reviews` service, in the `User.reviews` resolver, we should expect to see the field `user.nested1.nested2.a` provided in the `user` argument, but instead we only see `user.nested1.nested2.b`.

It appears that for doubly-nested fields, only the last `@requires` statement works correctly, and all other `@requires` statements that require fields within the same doubly-nested path are ignored.

## Expected Behavior

In the `User.reviews` resolver, the `user` argument passed in as the parent should contain all required fields specified for the `User.reviews` field (namely, `nested1.nested2.a`).

## Actual Behavior

The `user` argument does not contain the `nested1.nested2.a` field.

## Reproduction

A minimal reproduction can be found here: https://github.com/jakeblaxon/apollo-federation-requires-bug-demo

### PR DESCRIPTION
**Pull request by jakeblaxon**
This fixes a bug in the Apollo Gateway, where @requires fields are not provided to resolvers for fields nested more than one level deep.

## What this is trying to fix

This aims to fix issue #3848: [Federation Gateway] @requires directive sometimes does not provide all required fields

## Scenario

When requiring fields nested more than one level deep, they are not getting merged together into one selection set in the query plan. Instead, the query plan will contain duplicate sets like the following:

```graphql
A {
    nested1 {
        nested2 {
            requiredValue
        }
    }
    nested1 {
        nested2 {
            userSpecifiedValue
        }
    }
}
```

The required value would be fetched but overwritten by the second selection set in the javascript object. This PR solves this issue by merging the selection sets together, to arbitrary depth, like the following:

```graphql
A {
    nested1 {
        nested2 {
            requiredValue
            userSpecifiedValue
        }
    }
}
```

Fixes #3848
Closes #4017

### CODE REVIEW

**Comment by jakeblaxon** [comment]
Just noticed that #4017 appears to solve the same issue. I'll leave this PR open for now, but I'll go ahead and close it if #4017 gets merged in.

File: packages/apollo-gateway/src/FieldSet.ts [hunk 1]
```diff
@@ -10,6 +10,7 @@ import {
   GraphQLObjectType,
 } from 'graphql';
 import { getResponseName } from './utilities/graphql';
+import _ from 'lodash';
```
Comment (trevor-scheer) [inline packages/apollo-gateway/src/FieldSet.ts:13]: This is just a nitpick, but I'd prefer not to introduce `lodash` if we don't need to. In this case:
* `partition` exists within this repo under `/utilities/array.ts`.
* `groupBy` already exists within this repo, it could be moved from `FieldSet.ts` to the `/utilities/array.ts` file if the implementation is sufficient for your use case.

Comment (trevor-scheer) [reply packages/apollo-gateway/src/FieldSet.ts:13]: Sidenote, if for some reason we land on keeping it as-is based on discussion here, `lodash` needs to be added as a dependency to the gateway repo since it currently is not.

File: packages/apollo-gateway/src/__tests__/integration/requires.test.ts [hunk 2]
```diff
@@ -47,3 +51,362 @@ it('supports passing additional fields defined by a requires', async () => {
   expect(queryPlan).toCallService('product');
   expect(queryPlan).toCallService('books');
 });
+
+const serviceA: ServiceDefinitionModule = {
```
Comment (trevor-scheer) [inline packages/apollo-gateway/src/__tests__/integration/requires.test.ts:55]: I appreciate the rigor and depth of these test cases but they're admittedly a bit hard to reason about and validate (as a human). Is there any way we can apply the concepts here to our existing test fixtures? If that seems like a large ask (which would be understandable), can we humanize the types and field names in this example?

File: packages/apollo-gateway/src/__tests__/integration/requires.test.ts [hunk 3]
```diff
@@ -47,3 +51,362 @@ it('supports passing additional fields defined by a requires', async () => {
...
+    fragment testFragment on A {
+      nested2 {
+        nested3 {
+          nameA
+        }
+      }
+    }
+  `;
+
+  const { data } = await execute([serviceA, serviceB], {
```
Comment (trevor-scheer) [inline packages/apollo-gateway/src/__tests__/integration/requires.test.ts:395]: Can we get a snapshot of the query plan here as well please?

**Comment by trevor-scheer** [comment]
Also, please add a changelog entry to the gateway changelog. Note: there's a separate changelog for gateway from the rest of the server monorepo.

**Comment by jakeblaxon** [comment]
Thanks, @trevor-scheer! I can get these changes in soon. One concern I want to bring up though is that this only combines selection sets for field nodes. If we were to get a fragment node that itself had nested subfields, that fragment node's selection set would still potentially override the corresponding field node's. 

It currently appears that we expand any fragments into fields before calling `selectionSetFromFieldSet()`, so I haven't run into this issue, even when testing with fragments in the user query. I added the second test case, however, to catch this issue in case something changes in the future and we end up not expanding fragments before calling `selectionSetFromFieldSet()`.

I noticed that in the #4017 implementation, since we pass `context` into `selectionSetFromFieldSet()`, we can potentially solve this issue, since we would then have access to that fragment node's corresponding selection set. (The reason I didn't address the fragment case was because I didn't have access to the selection set directly from the fragment node). If we continue to expand fragments before building the query plan, then this won't be necessary. If we don't continue this, however, we may want to consider going with #4017 so we can address the fragment case.

Curious to hear your thoughts. Thanks!

**Comment by trevor-scheer** [comment]
@jakeblaxon the insight is very much appreciated. Let's go forward with this implementation. If we ever _do_ go down that path, we can revisit Lenny's solution or adapt things as needed. Let me know if you need anything from me!

File: packages/apollo-gateway/src/__tests__/integration/requires.test.ts (hunk 2 above)
Comment (jakeblaxon) [reply packages/apollo-gateway/src/__tests__/integration/requires.test.ts]: I agree, they're not very human readable. I updated them with @lennyburdette's tests, since they're much nicer. Thanks Lenny!

Comment (lennyburdette) [reply packages/apollo-gateway/src/__tests__/integration/requires.test.ts]: Glad we could collaborate! :grin:

File: packages/apollo-gateway/CHANGELOG.md [hunk 4]
```diff
@@ -4,7 +4,8 @@
 
 > The changes noted within this `vNEXT` section have not been released yet.  New PRs and commits which introduce changes should include an entry in this `vNEXT` section as part of their development.  When a release is being prepared, a new header will be (manually) created below and the appropriate changes within that release will be moved into the new section.
 
-- _Nothing yet! Stay tuned._
+- __FIX__: Collapse nested required fields into a single body in the query plan. Before, some nested fields' selection sets were getting split, causing some of their subfields to be dropped when executing the query. This fix collapses the split selection sets into one.
```
Comment (trevor-scheer) [inline packages/apollo-gateway/CHANGELOG.md:7]:
```suggestion
- __FIX__: Collapse nested required fields into a single body in the query plan. Before, some nested fields' selection sets were getting split, causing some of their subfields to be dropped when executing the query. This fix collapses the split selection sets into one. [#4064](https://github.com/apollographql/apollo-server/pull/4064)
```

File: packages/apollo-gateway/src/FieldSet.ts [hunk 5]
```diff
@@ -147,6 +129,38 @@ function mergeSelectionSets(fieldNodes: FieldNode[]): SelectionSetNode {
...
+    selections: mergeFieldNodeSelectionSets(selections),
   };
 }
+
+function mergeFieldNodeSelectionSets(
+  selectionNodes: SelectionNode[],
+): SelectionNode[] {
+  const [fieldNodes, fragmentNodes] = partition(
+    selectionNodes,
+    (node: SelectionNode): node is FieldNode => node.kind === 'Field',
```
Comment (trevor-scheer) [inline packages/apollo-gateway/src/FieldSet.ts:141]: Sorry I missed this on my first pass. When we check against `node.kind`, we prefer to use (in this case) `Kind.FIELD` rather than string itself by importing `Kind` from graphql-js.

**Comment by jakeblaxon** [comment]
@trevor-scheer Of course! Please add @lennyburdette as a co-author. Thank you!

**Comment by trevor-scheer** [comment]
Thank you both for your time and efforts here, I'll have this released as a patch fix early next week!

**Comment by abernix** [comment]
Published in `@apollo/gateway@0.16.2`! 🎉  Thanks for this contribution!
