### PR TITLE
Fix playground config typing error when in strictNull

### LINKED ISSUE #1713: Playground config requires all properties in TypeScript
ApolloServer constructor accepts parameter `playground?: PlaygroundConfig` where

```typescript
export type PlaygroundConfig =
  | RecursivePartial<PlaygroundRenderPageOptions>
  | boolean;
```

where

```typescript
type RecursivePartial<T> = {
  [P in keyof T]?: T[P] extends (infer U)[]
    ? RecursivePartial<U>[]
    : T[P] extends object ? RecursivePartial<T[P]> : T[P]
};
```

This results in TypeScript requiring one to define all playground options not just the ones that you want to override from defaults.

To reproduce just attempt to create an instance of ApolloServer with playground options not setting all available options:

```typescript
const server = new ApolloServer({
    playground: {
        settings: {
            "request.credentials": "include",
        },
    }
});
```

Failure to provide all options results in:
```
Types of property 'settings' are incompatible.
Argument of type '{ playground: { settings: { "request.credentials": string; }; }; }' is not assignable to parameter of type 'Config'.
  Types of property 'playground' are incompatible.
    Type '{ settings: { "request.credentials": string; }; }' is not assignable to type 'boolean | RecursivePartial<RenderPageOptions> | undefined'.
      Type '{ settings: { "request.credentials": string; }; }' is not assignable to type 'RecursivePartial<RenderPageOptions>'.
        Types of property 'settings' are incompatible.
          Type '{ "request.credentials": string; }' is not assignable to type 'ISettings'.
            Property ''general.betaUpdates'' is missing in type '{ "request.credentials": string; }'.
```

TypeScript version: `3.0.3`.

### PR DESCRIPTION
**Pull request by JacksonKearl**
Fixes #1713.

### CODE REVIEW

File: packages/apollo-server-core/src/playground.ts [hunk 1]
```diff
@@ -63,7 +63,7 @@ export function createPlaygroundOptions(
       }
     : { settings: undefined };
 
-  const playgroundOptions: PlaygroundRenderPageOptions = {
+  const playgroundOptions: any = {
```
Comment (JacksonKearl) [inline packages/apollo-server-core/src/playground.ts]: Do we want to put the time into type this properly? Seemed to open a can of worms when I tried, as everything that was `{ key1?: { key2: type } }` is now `{ key1?: { key2?: type } }`...
