### PR TITLE
apollo-server-core: use UserInputError for variable coercion errors

### LINKED ISSUE #3498: Wrong error code thrown for GraphQL validation failures in arguments using query variables
## Package Name/Version
Name: `apollo-server`

Version: `2.x.x`. All versions from `2.9.7` through `2.0.0` have this bug. 

## Expected Behavior
Queries that fail due to errors in scalar parsing should return the error code `GRAPHQL_VALIDATION_FAILED`.

## Actual Behavior
If an argument passed as a non-null query variable fails to validate, the server response has the code `INTERNAL_SERVER_ERROR`. This issue occurs with both built-in scalars and custom scalar types.

### Sandbox Link
https://codesandbox.io/s/apollo-error-code-bug-ho6vr

### Instructions
In the query field of the sandbox, enter
```
query($var:String!) {
  hello(name:$var)
}
```
And in the query variables section, enter
```
{
  "var": 2
}
```

The query above returns this response:
```
{
  "error": {
    "errors": [
      {
        "message": "Variable \"$var\" got invalid value 2; Expected type String. String cannot represent a non string value: 2",
        "locations": [
          {
            "line": 1,
            "column": 8
          }
        ],
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "stacktrace": [
              "TypeError: String cannot represent a non string value: 2",
              "    at GraphQLScalarType.coerceString [as parseValue] (/sandbox/node_modules/graphql/type/scalars.js:164:11)",
              "    at coerceInputValueImpl (/sandbox/node_modules/graphql/utilities/coerceInputValue.js:127:26)",
              "    at coerceInputValue (/sandbox/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
              "    at _loop (/sandbox/node_modules/graphql/execution/values.js:107:69)",
              "    at coerceVariableValues (/sandbox/node_modules/graphql/execution/values.js:119:16)",
              "    at getVariableValues (/sandbox/node_modules/graphql/execution/values.js:48:19)",
              "    at buildExecutionContext (/sandbox/node_modules/graphql/execution/execute.js:184:61)",
              "    at executeImpl (/sandbox/node_modules/graphql/execution/execute.js:89:20)",
              "    at Object.execute (/sandbox/node_modules/graphql/execution/execute.js:64:35)",
              "    at /sandbox/node_modules/apollo-server-core/dist/requestPipeline.js:240:46"
            ]
          }
        }
      }
    ]
  }
}
```

Type errors in arguments sent without using query variables, on the other hand, give a more accurate error code. Compare the above to the result for this query:

```
query {
  hello(name:2)
}
```

It gives the response
```
{
  "error": {
    "errors": [
      {
        "message": "Expected type String, found 2.",
        "locations": [
          {
            "line": 2,
            "column": 15
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Expected type String, found 2.",
              "    at isValidScalar (/sandbox/node_modules/graphql/validation/rules/ValuesOfCorrectType.js:159:27)",
              "    at Object.IntValue (/sandbox/node_modules/graphql/validation/rules/ValuesOfCorrectType.js:116:14)",
              "    at Object.enter (/sandbox/node_modules/graphql/language/visitor.js:324:29)",
              "    at Object.enter (/sandbox/node_modules/graphql/language/visitor.js:375:25)",
              "    at visit (/sandbox/node_modules/graphql/language/visitor.js:242:26)",
              "    at Object.validate (/sandbox/node_modules/graphql/validation/validate.js:73:24)",
              "    at validate (/sandbox/node_modules/apollo-server-core/dist/requestPipeline.js:212:32)",
              "    at Object.<anonymous> (/sandbox/node_modules/apollo-server-core/dist/requestPipeline.js:125:42)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/sandbox/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)"
            ]
          }
        }
      }
    ]
  }
}
```
which contains a much more useful error code for the client.

A similar problem was noted in several previous issues (#3361 #1410 #2204), but those issues were all linked to mutations, instead of queries.

### PR DESCRIPTION
**Pull request by glasser**
This particular error can be trivially triggered by clients, so it doesn't make
sense to use `INTERNAL_SERVER_ERROR` for it. It seems like a good fit for
`BAD_USER_INPUT`, which previously was only used if you explicitly throw a
`UserInputError` in your app.

Fixes #3498.

### CODE REVIEW

File: packages/apollo-server-errors/src/index.ts [hunk 1]
```diff
@@ -134,12 +134,16 @@ export function toApolloError(
...
+  // Sometimes it's more convenient to pass a function than a class name.
+  errorConstructor?: (message: string) => ApolloError;
   errorClass?: typeof ApolloError;
 }
 
 export function fromGraphQLError(error: GraphQLError, options?: ErrorOptions) {
   const copy: ApolloError =
-    options && options.errorClass
+    options && options.errorConstructor
+      ? options.errorConstructor(error.message)
```
Comment (glasser) [inline packages/apollo-server-errors/src/index.ts:145]: I did this because it turns out that `UserInputError` is not `typeof ApolloError`. The `ApolloError` constructor is `(message: string, code?: string, extensions?: Record<string, any>)` whereas the `UserInputError` constructor is `(message: string, properties?: Record<string, any>)` so there are valid calls to `new ApolloError("x", "y")` that can't be invoked on `new UserInputError`. (Other subclasses in this file just have `(message: string)` and I guess that's OK because additional arguments are just ignored?)

Now, fromGraphQLError only ever passes the first argument so both of those should be fine. But it doesn't work with `typeof ApolloError`. I did ask on [internal Slack](https://apollograph.slack.com/archives/C8MLN9S9H/p1617753079038400) to see if anyone has any ideas.

Comment (glasser) [reply packages/apollo-server-errors/src/index.ts]: Ah OK I think I figured it out.

File: packages/apollo-server-errors/src/index.ts [hunk 2]
```diff
@@ -134,7 +134,7 @@ export function toApolloError(
 
 export interface ErrorOptions {
   code?: string;
-  errorClass?: typeof ApolloError;
+  errorClass?: new (message: string) => ApolloError;
```
Comment (trevor-scheer) [inline packages/apollo-server-errors/src/index.ts:137]: This seems fine, maybe a comment here that explains, though I also think it's pretty self-explanatory if you look at it for a second.

FWIW, I tried to improve the type here a bit with no luck - I tried to make this "condition" into an interface that `UserInputError` could implement but TS wasn't having it.

**Review by trevor-scheer — APPROVED** [review]

File: packages/apollo-server-core/src/requestPipeline.ts [hunk 3]
```diff
@@ -451,16 +452,36 @@ export async function processGraphQLRequest<TContext>(
...
-          await didEncounterErrors(result.errors);
+        // The first thing that execution does is coerce the request's variables
+        // to the types declared in the operation, which can lead to errors if
+        // they are of the wrong type. We change any such errors into
+        // UserInputError so that their code doesn't end up being
+        // INTERNAL_SERVER_ERROR, since these are client errors.
+        const resultErrors = result.errors?.map((e) => {
+          if (
+            e.nodes?.length === 1 &&
+            e.nodes[0].kind === 'VariableDefinition' &&
```
[the remark this answers is not in the document]
Comment (glasser) [reply packages/apollo-server-core/src/requestPipeline.ts:463]: Sure, although TS actually does require the string constant here to be one of the possible valid strings (ie, typos won't compile).

File: packages/apollo-server-errors/src/index.ts (hunk 2 above)
Comment (glasser) [reply packages/apollo-server-errors/src/index.ts:137]: Added a comment. FWIW I find this type to be easier to understand than `typeof ApolloError` anyway. I think the lesson for the future is to just take functions rather than class names/constructors though... easy enough to pass `(s) => new MyClass(s)`...

**Comment by glasser** [comment]
Oh ah, you approved — will merge now.

File: packages/apollo-server-core/src/requestPipeline.ts [hunk 4]
```diff
@@ -451,16 +453,36 @@ export async function processGraphQLRequest<TContext>(
...
+        // INTERNAL_SERVER_ERROR, since these are client errors.
+        const resultErrors = result.errors?.map((e) => {
+          if (
+            e.nodes?.length === 1 &&
+            e.nodes[0].kind === Kind.VARIABLE_DEFINITION &&
+            e.message.startsWith(
+              `Variable "$${e.nodes[0].variable.name.value}" got invalid value `,
+            )
+          ) {
+            return fromGraphQLError(e, {
```
Comment (glasser) [inline packages/apollo-server-core/src/requestPipeline.ts:469]: I don't know why codecov thinks this is uncovered. There's a test!

**Comment by glasser** [comment]
I've released a prerelease with this fix, version `2.23.0-alpha.0`. Try out the alpha and see if it works for you! Please provide any feedback in #5094.

**Comment by glasser** [comment]
This is released in Apollo Server 2.23.0.
