### PR TITLE
Don't override custom code extensions from scalar parseValue errors

### LINKED ISSUE #7178: Error from GraphQLScalarType is not properly propagated to formatError hook
Hello,
we have a problem when throwing a `GraphQLError` from `GraphQLScalarType` in the new apollo v4. Before (in v3) it properly propagated the error into `formatError` hook but now it always changes its `extensions.code` to `BAD_USER_INPUT` and removes all additional fields.

This is happening only on errors thrown from `GraphQLScalarType` (e.g. errors from mutation/query resolvers work just fine) and only when we define GQL schema using `GraphQLSchema`. I tried [this example](https://www.apollographql.com/docs/apollo-server/schema/custom-scalars#example-restricting-integers-to-odd-values) where the schema is defined using  `typeDefs` and `resolvers` keys and it also worked.

<details>
<summary>Here is the code where you can reproduce the error.</summary>

```js
const { unwrapResolverError } = require('@apollo/server/errors');
const { ApolloServer } = require('@apollo/server');
const { startStandaloneServer } = require('@apollo/server/standalone');
const { GraphQLScalarType, GraphQLError } = require('graphql');
const { GraphQLSchema, GraphQLObjectType, GraphQLInputObjectType } = require('graphql');

const ColorScalarField = new GraphQLScalarType({
  name: 'ScalarField',
  serialize: (value) => value,
  parseValue: () => {
    console.log("Serializing")

    throw new GraphQLError('Scalar field custom error', {
      extensions: { code: 'CUSTOM_ERROR_CODE', extraErrorField: 123 },
    });
  },
  parseValue: () => {
    console.log("Parsing value")

    throw new GraphQLError('Scalar field custom error', {
      extensions: { code: 'CUSTOM_ERROR_CODE', extraErrorField: 123 },
    });
  },
  parseLiteral: () => {
    console.log("Parsing literal")

    throw new GraphQLError('Scalar field custom error', {
      extensions: { code: 'CUSTOM_ERROR_CODE', extraErrorField: 123 },
    });
  },
});

const ItemType = new GraphQLObjectType({
  name: 'item',
  fields: () => ({
    color: {
      type: ColorScalarField,
    },
  }),
});

const ItemUpdateType = new GraphQLInputObjectType({
  name: 'ItemUpdate',
  fields: () => ({
    color: {
      type: ColorScalarField,
    },
  }),
});

const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'Query',
    fields: () => ({
      item: {
        type: ItemType,
        description: 'Fetch the logged in user.',
        resolve: () => {},
      }
    }),
  }),
  mutation: new GraphQLObjectType({
    name: 'Mutation',
    fields: () => ({
      itemUpdate: {
        name: 'itemUpdate',
        args: {
          input: {
            type: ItemUpdateType,
          },
        },
        type: ItemType,
        resolve: () => {},
      }
    }),
  }),
});

const server = new ApolloServer({
  schema,
  debug: true,
  formatError: (err, err2) => {
    console.log("FORMAT ERROR:", err, err2)
    console.log("UNWRAPPED ERROR:", unwrapResolverError(err), unwrapResolverError(err2))

    return { err: 123 };
  }
});

(async () => {
  const { url } = await startStandaloneServer(server);
  console.log(`🚀 Server listening at: ${url}`);

  const response = await server.executeOperation({
    query: `
      mutation itemUpdate($input: ItemUpdate!) {
        itemUpdate(input: $input) {
          color
        }
      }
    `,
    variables: {
      input: {
        color: 'red',
      },
    },
  });

  console.log(response.body.singleResult.data)
  console.log(response.body.singleResult.errors)
})();
```
</details>

<details>

<summary>And here is the output.</summary>

```
Parsing value
FORMAT ERROR: {
  message: 'Variable "$input" got invalid value "red" at "input.color"; Scalar field custom error',
  locations: [ { line: 2, column: 27 } ],
  extensions: {
    code: 'BAD_USER_INPUT',
    stacktrace: [
      'GraphQLError: Variable "$input" got invalid value "red" at "input.color"; Scalar field custom error',
      '    at /test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/values.js:147:11',
      '    at coerceInputValueImpl (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:154:9)',
      '    at coerceInputValueImpl (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:117:34)',
      '    at coerceInputValueImpl (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:49:14)',
      '    at coerceInputValue (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:32:10)',
      '    at coerceVariableValues (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/values.js:132:69)',
      '    at getVariableValues (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/values.js:45:21)',
      '    at buildExecutionContext (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/execute.js:280:63)',
      '    at execute (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/execute.js:116:22)',
      '    at executeIncrementally (/test/node_modules/.pnpm/@apollo+server@4.1.1_graphql@16.6.0/node_modules/@apollo/server/dist/cjs/incrementalDeliveryPolyfill.js:47:34)'
    ]
  }
} GraphQLError: Variable "$input" got invalid value "red" at "input.color"; Scalar field custom error
    at /test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/values.js:147:11
    at coerceInputValueImpl (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:154:9)
    at coerceInputValueImpl (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:117:34)
    at coerceInputValueImpl (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:49:14)
    at coerceInputValue (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:32:10)
    at coerceVariableValues (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/values.js:132:69)
    at getVariableValues (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/values.js:45:21)
    at buildExecutionContext (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/execute.js:280:63)
    at execute (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/execute.js:116:22)
    at executeIncrementally (/test/node_modules/.pnpm/@apollo+server@4.1.1_graphql@16.6.0/node_modules/@apollo/server/dist/cjs/incrementalDeliveryPolyfill.js:47:34) {
  path: undefined,
  locations: [ { line: 2, column: 27 } ],
  extensions: { code: 'BAD_USER_INPUT' }
}
UNWRAPPED ERROR: {
  message: 'Variable "$input" got invalid value "red" at "input.color"; Scalar field custom error',
  locations: [ { line: 2, column: 27 } ],
  extensions: {
    code: 'BAD_USER_INPUT',
    stacktrace: [
      'GraphQLError: Variable "$input" got invalid value "red" at "input.color"; Scalar field custom error',
      '    at /test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/values.js:147:11',
      '    at coerceInputValueImpl (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:154:9)',
      '    at coerceInputValueImpl (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:117:34)',
      '    at coerceInputValueImpl (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:49:14)',
      '    at coerceInputValue (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:32:10)',
      '    at coerceVariableValues (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/values.js:132:69)',
      '    at getVariableValues (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/values.js:45:21)',
      '    at buildExecutionContext (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/execute.js:280:63)',
      '    at execute (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/execute.js:116:22)',
      '    at executeIncrementally (/test/node_modules/.pnpm/@apollo+server@4.1.1_graphql@16.6.0/node_modules/@apollo/server/dist/cjs/incrementalDeliveryPolyfill.js:47:34)'
    ]
  }
} GraphQLError: Variable "$input" got invalid value "red" at "input.color"; Scalar field custom error
    at /test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/values.js:147:11
    at coerceInputValueImpl (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:154:9)
    at coerceInputValueImpl (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:117:34)
    at coerceInputValueImpl (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:49:14)
    at coerceInputValue (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/utilities/coerceInputValue.js:32:10)
    at coerceVariableValues (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/values.js:132:69)
    at getVariableValues (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/values.js:45:21)
    at buildExecutionContext (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/execute.js:280:63)
    at execute (/test/node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/execution/execute.js:116:22)
    at executeIncrementally (/test/node_modules/.pnpm/@apollo+server@4.1.1_graphql@16.6.0/node_modules/@apollo/server/dist/cjs/incrementalDeliveryPolyfill.js:47:34) {
  path: undefined,
  locations: [ { line: 2, column: 27 } ],
  extensions: { code: 'BAD_USER_INPUT' }
}
undefined
[ { err: 123 } ]
```
</details>

I would expect the error received in `formatError` hook to have `extensions.code === 'CUSTOM_ERROR_CODE'` and `extensions.extraErrorField === 123`.

Is there anything we missed? Thank you for any help.

### PR DESCRIPTION
**Pull request by glasser**
Adding `BAD_USER_INPUT` is a nice default (and overrides the inappropriate default of `INTERNAL_SERVER_ERROR`) but if somebody has set a `code` already, we shouldn't override.

(Note that there's a separate issue where graphql-js throws out extensions from the thrown error itself and only pays attention to extensions on the error's originalError; we're trying to fix that in https://github.com/graphql/graphql-js/pull/3785 but this is orthogonal.)

Fixes #7178.

### CODE REVIEW

**Comment by glasser** [comment]
As a workaround, you can throw something like:

```
const e = new GraphQLError('message', {extensions: {my: 'extensions'}});
throw new GraphQLError(e.message, { originalError: e });
```

File: packages/server/src/requestPipeline.ts [hunk 1]
```diff
@@ -447,13 +447,18 @@ export async function processGraphQLRequest<TContext extends BaseContext>(
...
+      // isBadUserInputGraphQLError since perhaps that function will one day be
+      // changed to something we can get directly from graphql-js, but the
+      // `code` check is AS-specific.)
       //
       // This is hacky! Hopefully graphql-js will give us a way to separate
       // variable resolution from execution later; see
       // https://github.com/graphql/graphql-js/issues/3169
       const resultErrors = result.errors?.map((e) => {
-        if (isBadUserInputGraphQLError(e)) {
+        if (isBadUserInputGraphQLError(e) && !e.extensions?.code) {
```
Comment (trevor-scheer) [inline packages/server/src/requestPipeline.ts:461]: Might be better to check for nullish (if `0` or empty string are not crazy unreasonable codes)
```suggestion
        if (isBadUserInputGraphQLError(e) && e.extensions?.code != null) {
```

**Review by trevor-scheer — APPROVED** [review]

File: packages/server/src/requestPipeline.ts (hunk 1 above)
Comment (glasser) [reply packages/server/src/requestPipeline.ts:461]: I kinda think they are :) But sure.

File: packages/server/src/requestPipeline.ts [hunk 2]
```diff
@@ -447,13 +447,18 @@ export async function processGraphQLRequest<TContext extends BaseContext>(
...
+      // isBadUserInputGraphQLError since perhaps that function will one day be
+      // changed to something we can get directly from graphql-js, but the
+      // `code` check is AS-specific.)
       //
       // This is hacky! Hopefully graphql-js will give us a way to separate
       // variable resolution from execution later; see
       // https://github.com/graphql/graphql-js/issues/3169
       const resultErrors = result.errors?.map((e) => {
-        if (isBadUserInputGraphQLError(e)) {
+        if (isBadUserInputGraphQLError(e) && e.extensions?.code != null) {
```
Comment (glasser) [inline packages/server/src/requestPipeline.ts:461]:
```suggestion
        if (isBadUserInputGraphQLError(e) && e.extensions?.code == null) {
```

better like this though :)
