### PR TITLE
apollo-engine-reporting: fix reporting errors from backends

### LINKED ISSUE #3052: Apollo engine reporting blocks data and error propagation in '@apollo/gateway' managed federation deployment
**Using versions:**
@apollo/gateway 0.7.1
apollo-server-express 2.7.0
node 10.15.3

**Setup:**
Apollo managed federation gateway server. Local development on Mac, deployment to zeit/now v2.

**Expected:**
Apollo server produces a synthesised federated schema, passing/reformatting errors as produced by child services.

**Actual:**
If a graphql error is produced by a child service, the error message below is produced. 

```json
"errors": [
    {
      "message": "500: Internal Server Error",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "response": {
          "url": "https://engage.xxx.xxx/graphql",
          "status": 500,
          "statusText": "Internal Server Error",
          "body": {
            "errors": [
              {
                "message": "addProtobufError called after stopTiming!",
                "extensions": {
                  "code": "INTERNAL_SERVER_ERROR"
                }
              }
            ]
          }
        }
      }
    }
  ],
  "data": {
    "user": {
      "name": "Nick McIntosh",
      "stars": null
    }
  },
...
]
```

The query generating this error spans two services 
- users.xxx.xxx which is providing the name field fine
- engage.xxx.xxx which is responsible for the stars parameter, which produces a graphql error when not authenticated.

Searching the Apollo Server codebase, the error message originates from the `addProtobufError` method of `EngineReportingTreeBuilder` from `apollo-engine-reporting/src/treeBuilder.ts`. `addProtobufError` appears to be called when an error occurs in a child service; but I cannot see why it is after `stopTiming` has been called - perhaps someone familiar with the package may be able to see the issue.

### PR DESCRIPTION
**Pull request by zionts**
The extension stack executionDidEnd method gets called before didEncounterErrors
for GraphQL errors returned from execution (although confusingly the plugin
executionDidEnd method gets called after), which caused the assertion that
nothing gets added to the EngineReportingTreeBuilder after stopTiming to
fail. Fix by moving stopTiming to the last possible moment: format().

Actually test error reporting, including both kinds of rewriting.

Add a comment noting that backend parse and validation errors don't get
reported.

Fixes #3052.

### CODE REVIEW

**Comment by glasser** [comment]
I sent more details to Adam on slack as I'm in transit but:

- a much simpler fix is to move the stopTiming call to format(). The whole point of the state machine error checking is to ensure that data isn't lost because (eg) errors show up after the trace is rendered, so that's the most precise way of achieving that goal anyway

- these throws represent "shouldn't happen" programming errors in our code, not an erroneous use by our users or bad data, so if anything they should be more catastrophic, not less. Eg maybe the code up above that catches them and doesn't crash the program should detect some specific error type that means "Apollo server programming error" and treat them more drastically. Console.error would have meant this bug would have been found later!

**Comment by glasser** [comment]
Can you get a test for this PR? Look at the `reports a total duration that is longer than the duration of its resolvers` for an example of a test of federated tracing (outside the context of the gateway, but still testing integration with apollo-server)

File: packages/apollo-engine-reporting/src/treeBuilder.ts [hunk 1]
```diff
@@ -100,13 +109,6 @@ export class EngineReportingTreeBuilder {
     path: ReadonlyArray<string | number> | undefined,
     error: Trace.Error,
   ) {
-    if (!this.startHrTime) {
```
Comment (glasser) [inline packages/apollo-engine-reporting/src/treeBuilder.ts]: Why are we still removing this?

File: packages/apollo-engine-reporting/src/treeBuilder.ts [hunk 2]
```diff
@@ -15,6 +15,7 @@ export class EngineReportingTreeBuilder {
     [rootResponsePath, this.rootNode],
   ]);
   private rewriteError?: (err: GraphQLError) => GraphQLError | null;
+  private consolePrefix = '[apollo-engine-reporting]';
```
Comment (glasser) [inline packages/apollo-engine-reporting/src/treeBuilder.ts]: how is this helpful in errors? isn't the stack trace good enough?

**Comment by glasser** [comment]
and pr desc needs an update

File: packages/apollo-engine-reporting/src/treeBuilder.ts (hunk 2 above)
Comment (jacob-ebey) [reply packages/apollo-engine-reporting/src/treeBuilder.ts]: I'm a fan of this as it's a clearer indication that something is seriously fucked and it's not part of the implementing application.

Comment (glasser) [reply packages/apollo-engine-reporting/src/treeBuilder.ts]: ok, but in that case maybe the message should literally say it's an internal bug in the library?

**Comment by glasser** [comment]
I rewrote this.

File: packages/apollo-engine-reporting/src/federatedExtension.ts [hunk 3]
```diff
@@ -53,30 +53,27 @@ export class EngineFederatedTracingExtension<TContext = any>
...
-      };
-    }
-  }
-
   // The ftv1 extension is a base64'd Trace protobuf containing only the
   // durationNs, startTime, endTime, and root fields.
+  //
+  // Note: format() is only called after executing an operation, and
+  // specifically isn't called for parse or validation errors. Parse and validation
+  // errors in a federated backend will get reported to the end user as a downstream
```
Comment (zionts) [inline packages/apollo-engine-reporting/src/federatedExtension.ts]: hm... can we track this as an issue for followup at least? Seems like it would be useful to know if the query planner is sending sub-operations that fail validation :)

File: packages/apollo-engine-reporting/src/treeBuilder.ts [hunk 4]
```diff
@@ -6,6 +6,10 @@ import {
 } from 'graphql';
 import { Trace, google } from 'apollo-engine-reporting-protobuf';
 
+function internalError(message: string) {
+  return new Error(`[internal apollo-server error] ${message}`);
```
Comment (zionts) [inline packages/apollo-engine-reporting/src/treeBuilder.ts]: nit: I do think `apollo-engine-reporting` is probably more appropriate, or `internal apollo metrics reporting` if we want to avoid the term engine.

Comment (glasser) [reply packages/apollo-engine-reporting/src/treeBuilder.ts]: I mean that's in the stack trace?
