### PR TITLE
Fix type of `SchemaReporter.pollTimer`

### LINKED ISSUE #7768: schemaReporter pollTimer has incorrect type
### Issue Description

In packages/server/src/plugin/schemaReporting/schemaReporter.ts

pollTimer is typed as NodeJS.Timer, it is actually a timeout, so using node 18> types it is incompatible
with clearTimeout()

It should be:

`private pollTimer?: ReturnType<typeof setTimeout>;`

```
node_modules/@apollo/server/src/plugin/schemaReporting/schemaReporter.ts:90:20 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(timeoutId: string | number | Timeout | undefined): void', gave the following error.
    Argument of type 'Timer' is not assignable to parameter of type 'string | number | Timeout | undefined'.
      Property '[Symbol.dispose]' is missing in type 'Timer' but required in type 'Timeout'.
  Overload 2 of 2, '(id: number | undefined): void', gave the following error.
    Argument of type 'Timer' is not assignable to parameter of type 'number'.

90       clearTimeout(this.pollTimer);
                      ~~~~~~~~~~~~~~

  node_modules/@types/node/timers.d.ts:130:17
    130                 [Symbol.dispose](): void;
                        ~~~~~~~~~~~~~~~~
    '[Symbol.dispose]' is declared here.

```

### Link to Reproduction

N/A

### Reproduction Steps

Upgrade your node types to 18, but it is pretty obvious that the type is incorrect.

### PR DESCRIPTION
**Pull request by cwikla**
Fixes #7768

In `packages/server/src/plugin/schemaReporting/schemaReporter.ts`, `SchemaReporter.pollTimer` is typed as `NodeJS.Timer`, it is actually a `NodeJS.Timeout`, so using node 18> types it is incompatible
with `clearTimeout()`.

### CODE REVIEW

File: packages/server/src/plugin/schemaReporting/schemaReporter.ts [hunk 1]
```diff
@@ -40,7 +40,7 @@ export class SchemaReporter {
   private readonly fetcher: Fetcher;
 
   private isStopped: boolean;
-  private pollTimer?: NodeJS.Timer;
+  private pollTimer?: ReturnType<typeof setTimeout>;
```
Comment (trevor-scheer) [inline packages/server/src/plugin/schemaReporting/schemaReporter.ts:43]:
```suggestion
  private pollTimer?: NodeJS.Timeout;
```

**Review by trevor-scheer — CHANGES_REQUESTED** [review]
Thanks for the PR! Can you please add a patch changeset by running `npx changeset`?

File: packages/server/src/plugin/schemaReporting/schemaReporter.ts (hunk 1 above)
Comment (cwikla) [reply packages/server/src/plugin/schemaReporting/schemaReporter.ts]: Changed.

**Review by trevor-scheer — APPROVED** [review]
Perfect, thanks!
