### PR TITLE
Two unrelated small cache improvements

### LINKED ISSUE #6742: fqc prefix is added and there's no way to disable it
https://github.com/apollographql/apollo-server/blob/3bfe4e5c505c9ba00de17eace9091645fc4022d0/packages/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts#L165

We want to use redis for caching, and we want different processes to have access to only their keys.
We use redis permissions for prefixes, so process_1 could access keys `process_1*`.

I thought adding `generateCacheKey` was nice and could fix it all, but the `fqc` prefix is always there.

Can we just have total control over keys (in case one wants it, of course)?

### LINKED ISSUE #7240: Allow `cache: "bounded"` or fail quickly if it is passed
### Issue Description

In AS 3.9 we introduced `cache: "bounded"` as an easy way to shift to the newly-recommended-for-DOS-prevention behavior of not having an unbounded in-memory cache. In AS4 we made this behavior the default and stopped recognizing `cache: "bounded"`. Non-TypeScript users upgrading to AS4 may [miss the migration guide section stating that this is the default](https://www.apollographql.com/docs/apollo-server/migration/#default-cache-is-bounded) and in fact the migration guide does not state that the old value *no longer works*. While this is not a big deal for TS users (or `@ts-check` users) and it would be unreasonable for us to try to reproduce our API's entire set of compile-time checks at runtime, this particular change penalizes users who followed our recommended practices in 3.9 on, so it would be nice to either explicitly allow `cache: "bounded"` or to make it an immediate runtime failure (and update the migration guide).

### Link to Reproduction

caused problems here: https://github.com/apollographql/apollo-utils/pull/236

### Reproduction Steps

_No response_

### PR DESCRIPTION
**Pull request by glasser**
- Explicitly allow people to pass `cache: 'bounded'`. Non-TS users upgrading from the recommended AS3.9+ configuration could do this by accident. Fixes #7240.

- Upgrade `@apollo/utils.keyvaluecache` so that the new `PrefixingKeyValueCache.cacheDangerouslyDoesNotNeedPrefixesForIsolation` feature lets you disable prefixing for the APQ and full response caches. Throw if you try to pass such a cache to `ApolloServer` itself because that cache is designed to be shared across features. Migrate off of PrefixingKeyValueCache for `documentStore` so that its prefixing can't be disabled. Fixes #6742.

### CODE REVIEW

**Comment by glasser** [comment]
I put this in one PR because they touched similar code. A test would be nice but eh, we don't have any tests of passing `cache` at all...

File: packages/server/src/ApolloServer.ts [hunk 1]
```diff
@@ -214,6 +220,19 @@ export class ApolloServer<in out TContext extends BaseContext = BaseContext> {
 
     const isDev = nodeEnv !== 'production';
 
+    if (
+      config.cache &&
+      config.cache !== 'bounded' &&
```
Comment (trevor-scheer) [inline packages/server/src/ApolloServer.ts:225]: Can we log / warn when this is set? It'd be nice to re-remove this for good in v5

**Review by trevor-scheer — APPROVED** [review]
Should we leave the deps as-is all the packages besides server? I think those deps continue to be compatible and they're careted.

File: packages/server/src/ApolloServer.ts (hunk 1 above)
Comment (glasser) [reply packages/server/src/ApolloServer.ts:225]: You think so? I feel like it's not a huge deal and not worth bugging folks about (and if we have a very short migration guide for v5 then it's fine to remove it then without an explicit deprecation period).

Comment (trevor-scheer) [reply packages/server/src/ApolloServer.ts:225]: Yeah I don't feel too strongly about it, I guess the nice thing about the warning is it's simple and actionable: "you have a line of code that you can delete". I'm ok with leaving it though.

**Comment by glasser** [comment]
For the cache plugin we definitely want the upgrade. And integration test doesn't really matter either way. I guess the only one where not upgrading makes sense is gateway-interface... but I do kinda like trying to keep deps consistent to avoid accidental double installs?

Would like your thoughts on both these questions before I merge/release @trevor-scheer.

**Comment by trevor-scheer** [comment]
Nbd to upgrade them, go ahead and keep as is 👍
